version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017/tcp"
    environment:
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mymongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8082"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mymongo-data:
    driver:local
